version: "3"

tasks:
  default:
    desc: View all tasks
    cmds:
      - task --list-all
    silent: true

  dev:
    desc: Run app in dev mode (with proxy)
    env:
      PORT: '{{.PORT | default "8080"}}'
      PROXY_PORT: '{{.PROXY_PORT | default "3000"}}'
    cmds:
      - go tool gust -e 'task gen && exec go run ./cmd/server' -p "$PORT:$PROXY_PORT" --exclude out --exclude .git --exclude.glob '*_templ.go'
    silent: true

  run:
    desc: Run app
    cmds:
      - go run ./cmd/server
    silent: true

  build:
    desc: Build app binary
    deps:
      - gen
    cmds:
      - go build -o out/mymyapp-latest ./cmd/server
    silent: true

  format:
    desc: Format code
    cmds:
      - go fmt ./...
    silent: true

  gen:
    desc: Generate files
    deps:
      - gen:templ
    silent: true

  gen:templ:
    desc: Build templ files
    cmds:
      - go tool templ generate
    silent: true


  templ:fmt:
    desc: Format templ files
    cmds:
      - go tool templ fmt
    silent: true
